export const AscensionConfig = {
  minLevelToAscend: 10,
  soulPerLevelDivisor: 5,
  permanentUpgrades: [
    {
      id: "permDamage",
      name: "Eternal Power",
      description: "+10% Damage per level (permanen)",
      baseCost: 1,
      costGrowth: 1.5,
      maxLevel: 20,
      statKey: "damageMultiplier",
      valuePerLevel: 0.1,
    },
    {
      id: "permGold",
      name: "Eternal Wealth",
      description: "+10% Gold per level (permanen)",
      baseCost: 1,
      costGrowth: 1.5,
      maxLevel: 20,
      statKey: "goldMultiplier",
      valuePerLevel: 0.1,
    },
    {
      id: "permXp",
      name: "Eternal Wisdom",
      description: "+5% XP per level (permanen)",
      baseCost: 1,
      costGrowth: 1.5,
      maxLevel: 20,
      statKey: "xpMultiplier",
      valuePerLevel: 0.05,
    },
    {
      id: "permCrit",
      name: "Eternal Precision",
      description: "+1% Critical Chance per level (permanen)",
      baseCost: 2,
      costGrowth: 1.6,
      maxLevel: 10,
      statKey: "criticalChanceBonus",
      valuePerLevel: 0.01,
    },
    {
      id: "permOffline",
      name: "Eternal Patience",
      description: "+10% Offline Progress per level (permanen)",
      baseCost: 1,
      costGrowth: 1.5,
      maxLevel: 10,
      statKey: "offlineMultiplier",
      valuePerLevel: 0.1,
    },
  ],
};