export const EnemyTypes = {
  rat: {
    id: "rat",
    name: "Rat",
    level: 1,
    hp: 20,
    damage: 3,
    defense: 0,
    speed: 60,
    attackSpeed: 1,
    xpReward: 5,
    goldReward: 2,
    color: "#a3a3a3",
    size: { width: 20, height: 20 },
    aggroRadius: 120,
  },
  slime: {
    id: "slime",
    name: "Slime",
    level: 2,
    hp: 35,
    damage: 5,
    defense: 1,
    speed: 40,
    attackSpeed: 0.8,
    xpReward: 8,
    goldReward: 4,
    color: "#34d399",
    size: { width: 24, height: 24 },
    aggroRadius: 100,
  },
  goblin: {
    id: "goblin",
    name: "Goblin",
    level: 3,
    hp: 50,
    damage: 8,
    defense: 2,
    speed: 70,
    attackSpeed: 1.1,
    xpReward: 12,
    goldReward: 7,
    color: "#65a30d",
    size: { width: 26, height: 26 },
    aggroRadius: 140,
  },
  skeleton: {
    id: "skeleton",
    name: "Skeleton",
    level: 4,
    hp: 45,
    damage: 10,
    defense: 3,
    speed: 55,
    attackSpeed: 0.9,
    xpReward: 15,
    goldReward: 9,
    color: "#e5e7eb",
    size: { width: 24, height: 28 },
    aggroRadius: 130,
  },
  wolf: {
    id: "wolf",
    name: "Wolf",
    level: 5,
    hp: 60,
    damage: 12,
    defense: 2,
    speed: 100,
    attackSpeed: 1.3,
    xpReward: 20,
    goldReward: 11,
    color: "#78716c",
    size: { width: 28, height: 22 },
    aggroRadius: 160,
  },
};