export const BranchConfig = {
  combat: { label: "⚔️ Combat", color: "#f87171" },
  defense: { label: "🛡️ Defense", color: "#60a5fa" },
  economy: { label: "💰 Economy", color: "#facc15" },
};

export const SkillTreeConfig = {
  skills: [
    {
      id: "combat_attack",
      name: "Power Strike",
      description: "+2 Attack per level",
      branch: "combat",
      maxLevel: 5,
      cost: 1,
      prerequisites: [],
      effect: { statKey: "attack", valuePerLevel: 2 },
    },
    {
      id: "combat_crit",
      name: "Precision",
      description: "+1% Critical Chance per level",
      branch: "combat",
      maxLevel: 3,
      cost: 1,
      prerequisites: [{ id: "combat_attack", level: 3 }],
      effect: { statKey: "criticalChance", valuePerLevel: 0.01 },
    },
    {
      id: "defense_hp",
      name: "Vitality",
      description: "+10 Max HP per level",
      branch: "defense",
      maxLevel: 5,
      cost: 1,
      prerequisites: [],
      effect: { statKey: "maxHp", valuePerLevel: 10 },
    },
    {
      id: "defense_armor",
      name: "Iron Skin",
      description: "+1 Defense per level",
      branch: "defense",
      maxLevel: 3,
      cost: 1,
      prerequisites: [{ id: "defense_hp", level: 3 }],
      effect: { statKey: "defense", valuePerLevel: 1 },
    },
    {
      id: "economy_gold",
      name: "Golden Touch",
      description: "+10% Gold Gain per level",
      branch: "economy",
      maxLevel: 3,
      cost: 1,
      prerequisites: [],
      effect: { statKey: "goldMultiplier", valuePerLevel: 0.1 },
    },
    {
      id: "economy_xp",
      name: "Fast Learner",
      description: "+10% XP Gain per level",
      branch: "economy",
      maxLevel: 3,
      cost: 1,
      prerequisites: [{ id: "economy_gold", level: 2 }],
      effect: { statKey: "xpMultiplier", valuePerLevel: 0.1 },
    },
  ],
};